---
title: "Windowed Judgment"
author: "Daniel Klotz"
---


```{r setup7, include=FALSE, purl=FALSE}
  knitr::opts_chunk$set(eval = FALSE, tidy = FALSE, fig.align = 'center')
```

This chapter defines the function `judge_window`. It provides an low quality
option to get a static summary of the interactive functions `judge_explore` and 
`judge_compare`.

Here is an example of its use, together with an example plot:
```{r, purl=FALSE, eval=FALSE}
  coscos::libraries(coscos,
                    visCOS,
                    tidyverse,
                    ggridges)
  #
  cosdata <- coscos::viscos_example( ) %>%
    coscos::cook_cosdata()
  window_sizes <- c(10000, 25000)
  windows <- judge_window(cosdata,
                          of_metrics = list(nse = coscos::of_nse,
                                            kge = coscos::of_kge),
                          window_sizes = window_sizes)
```

Ideas for plots:
```{r, purl=FALSE, eval=FALSE}
# different line plots of the objective function
subset(windows$nse$QOBS_0002, le_group == "of_metric" ) %>%
  ggplot(data = .) +
    geom_line( aes(x = posixdate, y = value) ) +
    facet_wrap(~key, ncol = 3) +
  labs(title = "Objective Functions Windows for Basin 2")
ggplot(subset(windows$nse$QOBS_0002, le_group == "of_metric")) +
  geom_raster(aes(x = posixdate,
                  y = key,
                  fill = value)) +
  labs(title = "Objective Functions Windows for Basin 2")

# superimposed time series:
ggplot(windows$kge$QOBS_0001, aes(x = idx)) +
  facet_wrap(~le_group, scales = "free_y", ncol = 1) +
  geom_raster(data = subset(windows$nse$QOBS_0001,
                            le_group == "of_metric"),
              aes(x = posixdate,
                  y = key,
                  fill = value)) +
  geom_line(data = subset(windows$nse$QOBS_0001,
                          le_group == "q"),
            aes(x = posixdate,
                y = value,
                color = key)) +
  labs(title = "Objective Functions Windows for Basin 1")
```

