# Introduction

The goal of visCOS is to provide a possibility to streamline the R based 
visual-analysis for the hydrologcal model COSERO. COSERO is a HBV-like 
distributed rainfall-runoff model, developed at the institute for water 
management, hydrology and hydraulic engineering at BOKU, Vienna. The name is an
abbreviation for "Conceptual Semi-Distributed Rainfall Runoff Model".

visCOS consists of two parts, the current document and the R-package, and is
embedded into a broader effor which aims at establishing strong 
and easy to use workflows between R and COSERO. 

## Relation to other R-package
There exist many R-packages dedicated to hydrology.

Among then, several have provide help to the calibration of (conceptual)
rainfall-runoff models. As their name suggests, these models relate the a
rainfall input to a generated runoff for some given basins They have found
a wide array of applications in hydrology. Form the analysis of catchment
properties to climate impact studies, so to speak. From the point o view of the
R package ecosystem there are to packages, which are of particular interest with
regard to **visCOS**:
The [`hydroGOF`](https://CRAN.R-project.org/package=hydroGOF) package and the
[`hydroTSM`](https://CRAN.R-project.org/package=hydroTSM) package. The former
provides the most commonly used (and discussed) objective functions. The
latter, helps with the analysis, interpolation and the plotting of hydrological
time series.

As an R-package that aim of **visCOS** is to provide visual aids for 
the parameter estimation process of multiple (related) basins or catchments.

Thus, topic wise, **visCOS** can be positioned somewhere in-between the two 
previously mentioned packages. **visCOS** is usable for conceptual rainfall 
runoff models in general, but almost all of its functionality has been derived 
from different applications of the COSERO model. 

## Basic Concepts 

### Cooking Data
Within **visCOS** "cooking data" is is used as a synonym for the process of
transforming *raw data* into *cooked data*. This process and definitions are,
of course, metaphors. We shall explain them in the following.

### Raw Data
Raw-data is data which is not yet in the right format for its use. Raw-data
takes on many forms. The ones of interest for **visCOS** are series of
observations, $o$, and model simulations, $s$. in the scientific context, raw
data is usually served in some simple file format, e.g. *.txt* or *.csv*. In
other context more complex formats can be found, but we shall not delve into
that now. `R` includes method to read simple formats, e.g. with the different
`read.table` functions (simply enter `?read.table` in your `R` terminal to
get an overview). However, for larger (unstructured) files we recommend the read
functionality of the `data.table` package. In our tests it was fastest and most
flexible choice. Lastly, we recommend `readr` package for well structured and
large data that has to be read.

### Cooked Data
Cooked data is data that is formatted in a way, that can be used be used by
applications. A nice example (or dish if you want to) for cooked data is  
[tidy-data](ftp://cran.r-project.org/pub/R/web/packages/tidyr/vignettes/tidy-data.html).
 Another one might be the storage of data in matrices and vectors. Within
the **visCOS** package, cooked data, is data which is in the *cos_data* format.
This format is a slightly redundant but flexible representation of hydrological
time-series that is derived from the way COSERO produces outputs. All data in
*cos_data* format can be used for further exploratory analysis with the package.

...

Currently **visCOS** only allows to compare between *numbered catchments*! The
data **must** include an integer number at the end of its name, e.g.
`QObs_001` and `QSim_001`).
