# Other helpful functions 

Here you can find helpful functions that are not included in `viscos`.

```{r lruseful, include=FALSE}
  knitr::opts_chunk$set( fig.align = 'center')
```

```{r} 
  library(magrittr)
```

Get last `n` letters of a character: 
```{r}
substr_right <- function(x, n){
  # author: Simon Frey
  #
  # x ... character vector 
  # n ... number of letters to extract
  
  substr(x, nchar(x)-n+1, nchar(x))
}
substr_right("abcdefgh",5) %>% print(.)
```

Transform $mm$ into $\frac{m^3}{s}$.
```{r}
mm_to_m3s <- function(input, area = 1000, dt = 1) {
  # author: Simon Frey
  #
  # input ... Runoff in mm
  # area ... Area in m^2
  # dt ... timesetp in sec
  # output ... runoff m^3*s^-1
  
  return(output = input/(dt*1000)*area)
}
mm_to_m3s(1000,1,1) %>% print(.)
```

Transform  $\frac{m^3}{s}$ into $mm$.
```{r}
m3s_to_mm <- function(input, area = 1000, dt = 1) {
  # author: Simon Frey
  #
  # input ... Runoff in m^3*s^-1
  # area ... Area in m^2
  # dt ... timesetp in sec
  # output ... runoff mmm
  
  return(output = input*1000*dt/area)
}
m3s_to_mm(1,1,1) %>% print(.)
```

Check if a give year is a [leap year](http://en.wikipedia.org/wiki/Leap_year)
```{r}
is_leapyear = function(year) {
  # author: Simon Frey

  return(((year %% 4 == 0) & (year %% 100 != 0)) | (year %% 400 == 0))
}
```

