---
title: "Introduction"
author:
- "Daniel Klotz, Johannes Wesemann, Mathew Herrnegger"
date: "6 Juli 2016"
output: html_document
---

visCOS is still under (heavy) development. It is thus not recommended to use the package, yet.

---

There exist many hydrological R-packages.

Among them there are several that have the goal of providing aid to the calibration of hydrological models. In particular: The [`hydroGOF`](https://CRAN.R-project.org/package=hydroGOF) packages provides a set of commonly used (and disputed) objective functions. The [`hydroTSM`](https://CRAN.R-project.org/package=hydroTSM) package allows for the analysis, interpolation and plotting of hydrological time series. Topically, **visCOS** can be positioned between those two. In concrete, visCOS is an R-package that provides summaries and visualisation to aid the parameter estimation for conceptual rainfall-runoff models in general and COSERO in special.
COSERO is a HBV-like model that was developed at the
institute for water management, hydrology and hydraulic engineering (IWHW) at
BOKU, Vienna. The name is an abbreviation for "**Co**nceptual
**Se**mi-Distributed **R**ainfall Run**o**ff Model".
This page provides a hub to access the different examples and the entire program
code.

## Loading raw data
From the point of view of **visCOS** raw-data are time-series of observations
and model output. Usually raw data is saved in some simple file format,
e.g. *.txt* or *.csv*. `R` already includes many option to read those files
with the `read.table` functionalities.
For larger unstructured files the read options of the `data.table` package is
recommended. In our tests it was fastest and most flexible option.
Alternatively the `readr` can be used if the data is more structured and large.

**Note** at this stage, only a comparison between **numbered catchments**
 for two parameters is possible. So the data must include an integer
number after the description (like "QObs_001" and "QSim_001").

## The basic data structure
Shall follow

# The Package
**1. Basics**

- [Cooking Data](LP-cook_data.html)
- [Set Options](LP-viscos_options.html)

**2. Data Cooking**

- [Time aggregation](LP-aggregationsplots.html)
- [Objective Functions](LP-main_of.html)
- [Explore Runoff and Objective Functions](LP-explore_runoff.html)

**3. Plotlists**

- [Objective Function Plots](LP-plot_main_of.html)
- [Saving Plots](LP-serve.html)

**Other**

- [Defensive Code](LP-defensive_code.html)
- [Helper Funcitons](LP-helpers.html)
