---
title: "Ojective Functions"
author: 
- "Daniel Klotz, Johannes Wesemann, Mathew Herrnegger"
date: "14 Juli 2016"
output: html_document
---

```{r setup, include=FALSE, purl=FALSE}
  knitr::opts_chunk$set(eval = FALSE, tidy = FALSE)
```


# Introduction


# Code 
This section defines the code for different objective functions. If posisble the
calculation is done with the help of the `hydroGOF` package, if not an R-code
solution is tried. 
```{r}
#' Objective Functions
#' 
#' Different objective Functions, provided by visCOS. A detailed description 
#' of each of the provided objective function is provided in the respective
#' vignette
#' 
#' @param o The reference data or observations (o_data)
#' @param s The created data or the simulations (s_data)
#' @name of_overview
NULL
```


```{r}
#' Root Mean Sqaured Error 
#' 
#' @rdname of_overview
#' @import hydroGOF
#' @export
of_rmse <- function(o,s) {
  as.numeric( rmse(s,o) )
}
```

```{r}
#' Percentage Bias 
#' 
#' @rdname of_overview
#' @import hydroGOF
#' @export
of_pbias <- function(o,s) {
  as.numeric( pbias(s,o) )
}
```

```{r}
#' Nash-Sutcliffe Efficiency
#' 
#' @rdname of_overview
#' @import hydroGOF
#' @export
of_nse <- function(o,s) {
  as.numeric( NSE(s,o) )
}
```

```{r}
#' Inverted Nash-Sutcliffe Efficiency
#' 
#' @rdname of_overview
#' @import hydroGOF
#' @export
of_invert_nse <- function(o,s) {
  as.numeric( NSE(o,s) )
}
```

```{r}
#' Kling-Gupta Efficiency
#' 
#' @rdname of_overview
#' @import hydroGOF
#' @export
of_kge <- function(o,s) {
  as.numeric( KGE(s,o) )
}
```

```{r}
#' Correlation
#' 
#' @rdname of_overview
#' @import hydroGOF
#' @export
of_cor <- function(o,s) {
  diag( cor(o,s) )
}
```

```{r}
#' Ratio of Standard Deviations
#'
#' @rdname of_overview
#' @import hydroGOF
#' @export
of_rsd <- function(o,s) {
  as.numeric( rSD(s,o) )
}
```

```{r}
#' Ratio of Means
#'
#' @rdname of_overview
#' @export
of_rmeans <- function(o,s) {
  as.numeric( mean(s)/mean(o) )
}
```

```{r}
#' Volumetric Efficiency
#'
#' @rdname of_overview
#' @import hydroGOF
#' @export
of_ve <- function(o,s) {
  as.numeric( VE(s,o) )
}
```
