---
title: "visCOS - Options"
author: 
- "Daniel Klotz, Johannes Wesemann"
date: "11 Juli 2016"
output: 
  html_document:
    number_sections: yes
---

```{r setup, include=FALSE, purl=FALSE}
knitr::opts_chunk$set(eval = FALSE, tidy = FALSE)
```

# Introduction 
This section defines code of the visCOS functions used to set and adapt the 
visCOS options. With the added comments code is pretty much self-explanatory. 

```{r}
#' visCOS global options
#' 
#' Get and set the global options of visCOS
#' 
#' These are the options you can adapt by executing the function 
#' (default values)
#' \preformatted{
#'   viscos_options(
#'    # data.frame column names
#'       name_data1 = "qobs", # name of the first time-series data (observations)  
#'       name_data2 = "qsim", # name of the second time-series data (simulations)  
#'       name_COSyear = "yyyy", # name of year-column
#'       name_COSmonth = "mm",  # name of month-column
#'       name_COSday = "dd",  # name of day-column
#'       name_COShour = "hh", # name of hour-column
#'       name_COSmin = "min", # name of minute-column
#'       name_COSposix = "posixdate", # name of the complete-date-column
#'       name_COSperiod = "period", # name of the marked-period column
#'    # plot options
#'       color_data1 = "steelblue", # color associated with the first time-series data
#'       color_data2 = "orange",  # color associated with the second time-series data
#'       legend_title = "legend", 
#'       xlab = "year",
#'       color_of_low = 'darkred', # color associated with a bad objective function 
#'       olor_of_mid = 'grey', # color associated with an average objective function 
#'       color_of_high = 'magenta', # color associated with a high objective function 
#'       midpoint = 0.5,
#'       limits = c(0,1)
#'   )
#' }
#'
#' @examples
#' viscos_options("name_data1")
#' viscos_options(name_data1 = "OtherData")
#' viscos_options("name_data1")
#' @export
viscos_options <- GlobalOptions::setGlobalOptions( 
  # data.frame column names
  name_data1 = "qobs", 
  name_data2 = "qsim", 
  name_COSyear = "yyyy",
  name_COSmonth = "mm",
  name_COSday = "dd",
  name_COShour = "hh",
  name_COSmin = "min",
  name_COSposix = "posixdate",
  name_COSperiod = "period",
 # plot options
  color_data1 = "steelblue", 
  color_data2 = "orange",
  color_of_low = 'darkred',
  color_of_mid = 'magenta',
  color_of_high = 'green',
  midpoint = 0.5,
  limits = c(0,1)
)

```

